# NOTE: Current plan gives 1500 build minutes per month.
version: 2
jobs:
  test:
    docker:
      # Available from https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/bwplotka/mimic
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
            version: 17.07.0-ce
      - run: make check-go-mod
      - run: make lint
      # Uncomment below once https://github.com/raviqqe/liche/issues/25 is fixed.
      # - run: make check-docs
      - run: make format
      - run:
          name: "Run all tests"
          command: |
            make test

workflows:
  version: 2
  thanos:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
